### ISSUE TITLE
[v2.1] testing of build 2.1.0.v20161102-1515

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#104]
I need help with testing of the build
tag: **...**
commit: **7ce68498903be40a66d5f04733225c8cc64015b2**

It is available at the testing update site now: http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.1.0.v20161102-1515**

**Use "Help | Install New Software...", paste the link and select the right version!**

fixed issues:
- [x] #76 [v2.0] Steps to build the plugin using the source code
- [x] #98 add support for PowerCmd
- [x] #99 add support iTerm2 in Mac
- [x] #100 add open with Default application for Mac OS X

preliminary fixes, to be verified and may change:
- [x] #103 After copied file path, a tool-tip "Copied to clipboard" always exists.

new found issues and enhancement requests:
- [ ] #18 check compatibility to other terminal emulators
- [ ] #102 Menu contains each item twice on Mac OS (by default)
- [ ] #106 [v2.0] keyboard shortcuts are not working in popup menu under Linux
- [ ] #107 [v2.0] add support for external files
- [ ] #108 add mate-terminal support
- [ ] #109 add mate Caja (MATE) file browser support
- [ ] #110 LXDE: add lxterminal support

**Comment by vector090** [comment]
Hi, I would like to get this build and verify #103, but seem the URL is not available?

**Comment by anb0s** [comment]
It'a an eclipse update site --> use Help | Install New Software... Paste the link and select the build:
![image](https://cloud.githubusercontent.com/assets/95811/19958666/5a0f2e10-a1a1-11e6-82ac-a3117a036440.png)

**Comment by vector090** [comment]
Works fine!

**Comment by anb0s** [comment]
Thanks for your feedback!

**Comment by anb0s** [comment]
next build #111
