### ISSUE TITLE
[v2.1] testing of build 2.1.0.v20161103-2010

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#111]
I need help with testing of the build
tag: **...**
commit: **71c5a9a8e8b90fb2b38296fb149257921a290cb7**

It is available at the testing update site now: http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.1.0.v20161103-2010**

**Use "Help | Install New Software...", paste the link and select the right version!**

new fixed issues in this build:
- [x] #18 check compatibility to other terminal emulators
- [x] #102 Menu contains each item twice on Mac OS (by default)
- [x] #106 [v2.0] keyboard shortcuts are not working in popup menu under Linux
- [x] #107 [v2.0] add support for external files
- [x] #108 add mate-terminal support
- [x] #109 add mate Caja (MATE) file browser support
- [x] #110 LXDE: add lxterminal support

fixed issues with previous build(s):
- [x] #104 [v2.1] testing of build 2.1.0.v20161102-1515
  - [x] #76 [v2.0] Steps to build the plugin using the source code
  - [x] #98 add support for PowerCmd
  - [x] #99 add support iTerm2 in Mac
  - [x] #100 add open with Default application for Mac OS X
  - [x] #103 After copied file path, a tool-tip "Copied to clipboard" always exists.

new found issues and enhancement requests:
- [ ] #112 add linux guake support
- [ ] #113 add linux krusader support

**Comment by anb0s** [comment]
new test build #117
