### ISSUE TITLE
[v2.2] testing of build 2.2.0.v20181108-1757

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#169]
I need help with testing of the build
tag: **...**
commit: **1ce137ac9cc51101743574f324f4ae0dfa8b33d4**

It is available at the testing update site now: http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.2.0.v20181108-1757**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:

new fixed issues in this build:
- [x] #160 add support for CDT include and binary containers
- [x] #162 add support for CDT include browser
- [x] #168 "Copy Qualified Name to Clipboard" does not work in editor
- [x] added CDT SKD to all target platforms
- [x] added all target platforms to Travis CI build matrix
- [x] added target platform for Eclipse Photon (4.8)
- [x] set Eclipse 4.8 (Photon) as default target
- [x] removed openjdk7, because new Tycho (>=0.25) needs Java 8
- [x] README wth-Eclipse logo
- [x] moved GitHub related files to .github
- [x] updated copyright year to 2018
- [x] added oraclejdk9 to build matrix
- [x] Update tycho version to 1.2.0
- [x] updated the version to 2.2.0 and minimum Java 8 (JavaSE 1.8)
- [x] added openjdk10 and oraclejdk10
- [x] added Eclipse Photon 4.9 (2018-09) target platform
- [x] removed oraclejdk10 and added openjdk11

fixed issues with previous build(s):
...

**Comment by anb0s** [comment]
next testing see #174
