### ISSUE TITLE
[v2.2] testing of build 2.2.0.v20191004-1015

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#174]
I need help with testing of the build
tag: **...**
commit: **027edfa6a62d3c6e177d65a96f2f6a698ded5ba7**

It is available at the testing update site now: http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.2.0.v20191004-1015**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:

new fixed issues in this build:
- [x] #173 Change default command for cygwin
- [x] removed some not needed platforms (Eclipse-4.7, 2018-09, 2019-03)
- [x] removed oraclejdk8, because it's not supported by Travis CI anymore
- [x] updated tycho to 1.4.0
- [x] added Eclipse-2019-09 target platform and set Eclipse-2019-06 as default
- [x] #172 RFE: Change License to EPL 2.0
- [x] added Eclipse-2019-06 target platform and set Eclipse-2019-03 as default
- [x] #171 EasyShell does not compile with target platform Eclipse-2018-12 and greater
- [x] updated tycho to 1.3.0
- [x] set default target platform to Eclipse-2018-12 and added all to travis
- [x]  updated target platforms 2018-09 - 2019-03
- [x] removed JDK9 & 10 from CI matrix, because we want use only LTS versions

fixed issues with previous build(s):
- [x] #160 add support for CDT include and binary containers
- [x] #162 add support for CDT include browser
- [x] #168 "Copy Qualified Name to Clipboard" does not work in editor
- [x] added CDT SKD to all target platforms
- [x] added all target platforms to Travis CI build matrix
- [x] added target platform for Eclipse Photon (4.8)
- [x] set Eclipse 4.8 (Photon) as default target
- [x] removed openjdk7, because new Tycho (>=0.25) needs Java 8
- [x] README wth-Eclipse logo
- [x] moved GitHub related files to .github
- [x] updated copyright year to 2018
- [x] added oraclejdk9 to build matrix
- [x] Update tycho version to 1.2.0
- [x] updated the version to 2.2.0 and minimum Java 8 (JavaSE 1.8)
- [x] added openjdk10 and oraclejdk10
- [x] added Eclipse Photon 4.9 (2018-09) target platform
- [x] removed oraclejdk10 and added openjdk11

**Comment by anb0s** [comment]
see next build #179
