### ISSUE TITLE
[v2.2] testing of build 2.2.0.v20200919-1950

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#179]
I need help with testing of the build
tag: **V2_2_BETA_3**
commit: **71f48fe1215fb47834c830cf2d979c58b337a093**

It is available at the testing update site now: http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.2.0.v20200919-1950**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:

new fixed issues in this build:
- [x] #151 EasyShell context menu option not showing in STS 3.8.4.RELEASE Navigator View 
- [x] #178 improve dynamic popup menu support
- [x] #176 add tooltip with command string to menu entries
- [x] Remove wrong entry clipboard with EasyShell Run
- [x] Fix logo link and build badget
- [x] use tycho 1.7.0
- [x] set default platform to Eclipse-2020-06 
- [x] add new Eclipse-2020-xy and remove old Eclipse-2019-xy platforms 
- [x] use Eclipse-2019-12 platform and removed Eclipse-2018-12 
- [x] Set up CI with Azure Pipelines
- [x] use tycho 1.5.0 and Eclipse-2019-09 platform

fixed issues with previous build "[v2.2] testing of build 2.2.0.v20191004-1015 #174"
- [x] #173 Change default command for cygwin
- [x] removed some not needed platforms (Eclipse-4.7, 2018-09, 2019-03)
- [x] removed oraclejdk8, because it's not supported by Travis CI anymore
- [x] updated tycho to 1.4.0
- [x] added Eclipse-2019-09 target platform and set Eclipse-2019-06 as default
- [x] #172 RFE: Change License to EPL 2.0
- [x] added Eclipse-2019-06 target platform and set Eclipse-2019-03 as default
- [x] #171 EasyShell does not compile with target platform Eclipse-2018-12 and greater
- [x] updated tycho to 1.3.0
- [x] set default target platform to Eclipse-2018-12 and added all to travis
- [x]  updated target platforms 2018-09 - 2019-03
- [x] removed JDK9 & 10 from CI matrix, because we want use only LTS versions

fixed issues with previous build(s):
- [x] #160 add support for CDT include and binary containers
- [x] #162 add support for CDT include browser
- [x] #168 "Copy Qualified Name to Clipboard" does not work in editor
- [x] added CDT SKD to all target platforms
- [x] added all target platforms to Travis CI build matrix
- [x] added target platform for Eclipse Photon (4.8)
- [x] set Eclipse 4.8 (Photon) as default target
- [x] removed openjdk7, because new Tycho (>=0.25) needs Java 8
- [x] README wth-Eclipse logo
- [x] moved GitHub related files to .github
- [x] updated copyright year to 2018
- [x] added oraclejdk9 to build matrix
- [x] Update tycho version to 1.2.0
- [x] updated the version to 2.2.0 and minimum Java 8 (JavaSE 1.8)
- [x] added openjdk10 and oraclejdk10
- [x] added Eclipse Photon 4.9 (2018-09) target platform
- [x] removed oraclejdk10 and added openjdk11

**Comment by anb0s** [comment]
see new build #180
