### ISSUE TITLE
[v2.2] testing of build 2.2.0.v20201004-2044

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#180]
I need help with testing of the build
tag: **V2_2_RC1**
commit: **5b1baa89857d672d69426f4f3d21244a983afee6**

It is available at the testing update site now: http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.2.0.v20201004-2044**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:
- [ ] #181 Short-Cut Alt+R in conflict with Eclipse-Main-Menu Run Short-Cut Alt+R
- [ ] #183 java.lang.NoClassDefFoundError: org/eclipse/cdt/core/model/IIncludeReference

new fixed issues in this build:
- [x] #164 open in Explorer from "Open Resource" window
- [x] #74 add "Open With" support
- [x] #33 add support of editor selections
- [x] #15 ability to put the items in the main menu not in the "EasyShell" sub-menu
- [x] remove not used propertyTesters

fixed issues with previous build "[v2.2] testing of build 2.2.0.v20200919-1950 #179"
- [x] #151 EasyShell context menu option not showing in STS 3.8.4.RELEASE Navigator View 
- [x] #178 improve dynamic popup menu support
- [x] #176 add tooltip with command string to menu entries
- [x] Remove wrong entry clipboard with EasyShell Run
- [x] Fix logo link and build badget
- [x] use tycho 1.7.0
- [x] set default platform to Eclipse-2020-06 
- [x] add new Eclipse-2020-xy and remove old Eclipse-2019-xy platforms 
- [x] use Eclipse-2019-12 platform and removed Eclipse-2018-12 
- [x] Set up CI with Azure Pipelines
- [x] use tycho 1.5.0 and Eclipse-2019-09 platform

fixed issues with previous build "[v2.2] testing of build 2.2.0.v20191004-1015 #174"
- [x] #173 Change default command for cygwin
- [x] removed some not needed platforms (Eclipse-4.7, 2018-09, 2019-03)
- [x] removed oraclejdk8, because it's not supported by Travis CI anymore
- [x] updated tycho to 1.4.0
- [x] added Eclipse-2019-09 target platform and set Eclipse-2019-06 as default
- [x] #172 RFE: Change License to EPL 2.0
- [x] added Eclipse-2019-06 target platform and set Eclipse-2019-03 as default
- [x] #171 EasyShell does not compile with target platform Eclipse-2018-12 and greater
- [x] updated tycho to 1.3.0
- [x] set default target platform to Eclipse-2018-12 and added all to travis
- [x]  updated target platforms 2018-09 - 2019-03
- [x] removed JDK9 & 10 from CI matrix, because we want use only LTS versions

fixed issues with previous build(s):
- [x] #160 add support for CDT include and binary containers
- [x] #162 add support for CDT include browser
- [x] #168 "Copy Qualified Name to Clipboard" does not work in editor
- [x] added CDT SDK to all target platforms
- [x] added all target platforms to Travis CI build matrix
- [x] added target platform for Eclipse Photon (4.8)
- [x] set Eclipse 4.8 (Photon) as default target
- [x] removed openjdk7, because new Tycho (>=0.25) needs Java 8
- [x] README wth-Eclipse logo
- [x] moved GitHub related files to .github
- [x] updated copyright year to 2018
- [x] added oraclejdk9 to build matrix
- [x] Update tycho version to 1.2.0
- [x] updated the version to 2.2.0 and minimum Java 8 (JavaSE 1.8)
- [x] added openjdk10 and oraclejdk10
- [x] added Eclipse Photon 4.9 (2018-09) target platform
- [x] removed oraclejdk10 and added openjdk11

**Comment by makkimesser** [comment]
Just tried out 2.2.0 and got this exception:

`
java.lang.NoClassDefFoundError: org/eclipse/cdt/core/model/IIncludeReference
        at de.anbos.eclipse.easyshell.plugin.commands.DefineCommands.createContributionItems(DefineCommands.java:53)
        at org.eclipse.ui.internal.menus.ContributionFactoryGenerator.compute(ContributionFactoryGenerator.java:73)
        at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.mergeFactoryIntoModel(ContributionRecord.java:272)
        at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.mergeIntoModel(ContributionRecord.java:216)
        at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processAddition(MenuManagerRenderer.java:551)
        at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.generateContributions(MenuManagerRenderer.java:530)
        at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.processContributions(MenuManagerRenderer.java:498)
        at org.eclipse.ui.internal.PopupMenuExtender.addMenuContributions(PopupMenuExtender.java:382)
        at org.eclipse.ui.internal.PopupMenuExtender.menuAboutToShow(PopupMenuExtender.java:355)
        at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:338)
        at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:468)
        at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:463)
        at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:495)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4195)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1042)
        at org.eclipse.swt.widgets.Control.WM_INITMENUPOPUP(Control.java:5156)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:4788)
        at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
        at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
        at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2142)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4913)
        at org.eclipse.swt.internal.win32.OS.TrackPopupMenu(Native Method)
        at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:237)
        at org.eclipse.swt.widgets.Display.runPopups(Display.java:4053)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3606)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.ClassNotFoundException: org.eclipse.cdt.core.model.IIncludeReference cannot be found by de.anbos.eclipse.easyshell.plugin_2.2.0.v20201004-2044
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 50 more
`

**Comment by makkimesser** [comment]
See you specified the dependency to `cdt.core` as optional in plugin-manifest. Maybe this is the reason why it is not loaded during installation?

After switching back to 2.1.0 it runs again without problems.

**Comment by anb0s** [comment]
Thank you for the report! Yes i think it's related to the optional dependency to CDT, but it should be optional...
I will investigate, see issue #183

**Comment by anb0s** [comment]
pushed new testing build see #192
