### ISSUE TITLE
[v2.0] issues found in beta 3

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#68]
I need help with testing of the next test release beta 3
tag: V2_0_0_BETA_3_HOT_FIX
commit: cafa724e2c0b934bdec80520d461e0b4338ff7d9

It is available at the testing site now:
http://anb0s.github.io/EasyShell/testing
version: EasyShell 2.0.0.v20160726-2133

![image](https://cloud.githubusercontent.com/assets/95811/17156428/12c5ae86-538a-11e6-81d3-2adac965c6d1.png)

open issues (verified, new, fixed for next beta):
- [x] #16 Copy Fully Qualified Class Name
- [ ] #46 [v2.0] [regression] add key bindings again
- [ ] #47 [v2.0] add popup menu with key binding support
- [x] #51 please support https://github.com/cmderdev/cmder
- [ ] #55 [v2.0] migration support from legacy EasyShell v1.x
- [ ] #62 [v2.0] To be able to target a file or a directory only
- [ ] #63 [v2.0] make possible to add a menu as sub menu
- [x] #72 [v2.0] add *_path eclipse variables
- [ ] #73 add support for list parameters
- [ ] #75 add "var..." button instead or additionally to double click to add variables
- [x] #77 add git-bash.exe (Git for Windows 2.x) preset

needed for release:
- [ ] #34 [v2.0] prepare release
- [ ] #37 [v2.0] update project description: new features, how to use, how to migrate from 1.x
- [ ] #38 [v2.0] update sourceforge binaries and close all issues there
- [ ] #39 [v2.0] update Eclipse Marketplace

**Comment by anb0s** [comment]
v2.0.0 beta 3 build available at site: http://anb0s.github.io/EasyShell/testing
version: EasyShell 2.0.0.v20160726-2110

![image](https://cloud.githubusercontent.com/assets/95811/17155783/e1340bb8-5386-11e6-9474-b1511e5be79b.png)

**Comment by anb0s** [comment]
Because of vacation the beta 3 will be until 15.08.2016 now. Then i will push RC1 for one week and hope make the release of v2.0 at 22.08.2016. Thanks!

**Comment by anb0s** [comment]
I need more time and just release beta 4. RC1 will follow in few days...

**Comment by anb0s** [comment]
see #78
