### ISSUE TITLE
[v2.0] issues found in RC1

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#80]
I need help with testing of the next test release RC1
tag: **V2_0_0_RC1**
commit: **e2847ed6fb392d351e1ac2e81945a96b6dd4c4bf**

It is available at the testing site now:
http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.0.0.v20160919-1856**

![image](https://cloud.githubusercontent.com/assets/95811/18645218/a9e757d6-7eac-11e6-99a8-cee55c6187d1.png)

open issues (verified, new, fixed for next beta):
- [x] #48 [v2.0] add content assist to tool / presets definition
- [ ] #62 [v2.0] To be able to target a file or a directory only
- [x] #75 [v2.0] add "var..." button instead or additionally to double click to add variables
- [ ] #79 [v2.0] add new icons
- [x] #86 [v2.0] [popup menu] do not show if empty or only one entry
- [x] #87 [v2.0] "Up" and "Down" are working, but entries are reordered wrongly

needed for release:
- [ ] #34 [v2.0] prepare release
- [ ] #37 [v2.0] update project description: new features, how to use, how to migrate from 1.x
- [ ] #38 [v2.0] update sourceforge binaries and close all issues there
- [ ] #39 [v2.0] update Eclipse Marketplace

**Comment by anb0s** [comment]
see #88
