### ISSUE TITLE
[v2.0] issues found in RC2

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#88]
I need help with testing of the next test release RC2
tag: **V2_0_0_RC2**
commit: **147a25ee0d96731ce51a6d0ab2b534f059d4fdf9**

It is available at the testing site now:
http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.0.0.v20160923-1117**

![image](https://cloud.githubusercontent.com/assets/95811/18784214/ec278f6c-8190-11e6-9e30-908268275545.png)

open issues (verified, new, fixed for next beta):
- [x] #62 [v2.0] To be able to target a file or a directory only
- [x] #79 [v2.0] add new icons
- [x] #90 [v2.0] add dialog for multiple command selection
- [x] #91 [v2.0] [content assist] if using $ or { the variable is copied with additional ${
- [x] #92 [v2.0] make content assist available in all edit fileds with variable support
- [x] #93 [v2.0] add variables for resource name without extension and resource extension

needed for release:
- [ ] #34 [v2.0] prepare release
- [ ] #37 [v2.0] update project description: new features, how to use, how to migrate from 1.x
- [ ] #38 [v2.0] update sourceforge binaries and close all issues there
- [ ] #39 [v2.0] update Eclipse Marketplace

**Comment by anb0s** [comment]
see #94
