### ISSUE TITLE
[v2.0] issues found in RC3

### ISSUE THREAD

**Issue by anb0s** [anb0s/EasyShell#94]
I need help with testing of the next test release RC3
tag: **V2_0_0_RC3**
commit: **67f9adf65408b5b92fb676d962bab0bad9233769**

It is available at the testing site now:
http://anb0s.github.io/EasyShell/testing
version: **EasyShell 2.0.0.v20160927-2006**

![image](https://cloud.githubusercontent.com/assets/95811/18889925/71c8fb80-84ff-11e6-8e32-f9f6cce622ad.png)

open issues (verified, new, fixed for next beta):

needed for release:
- [x] #34 [v2.0] prepare release
- [x] #37 [v2.0] update project description
- [x] #38 [v2.0] update sourceforge binaries and close all issues there
- [x] #39 [v2.0] update Eclipse Marketplace
